const $=s=>document.querySelector(s);
const types={STANDARD:'正式标准',ENTERPRISE_STANDARD:'企业/院内标准',TYPICAL_DESIGN:'典型设计',PROJECT_EXPERIENCE:'历史项目经验',PERSONAL_RULE:'个人设计判据',MANUFACTURER:'厂家资料'};
let docs=[],conversationId=null,lastAnswer=null,editingRule=null,allRules=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){const r=await fetch('/api'+path,opts);const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function notice(text){$('#notice').textContent=text;$('#notice').hidden=!text;}
async function safe(action){notice('');try{return await action();}catch(e){notice(e.message);}}
function json(data,method='POST'){return{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)};}
function view(name){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===name));$('#page-title').textContent={chat:'规范查询',library:'规范库',rules:'设计判据',settings:'系统设置'}[name];if(name==='library')safe(loadDocs);if(name==='rules')safe(loadRules);if(name==='settings')safe(loadSettings);}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
const welcome=$('#messages').innerHTML;
function bindExamples(){document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{$('#question').value=b.dataset.question;$('#question').focus();});}bindExamples();
$('#new-chat').onclick=()=>{conversationId=null;$('#messages').innerHTML=welcome;$('#evidence-list').innerHTML='<div class="empty">查询后显示来源</div>';bindExamples();view('chat');};
function citation(row,i){return `<button class="citation" data-clause="${esc(row.id)}"><strong>[${i+1}] ${esc(row.standard_code||'编号未录入')}</strong>${esc(row.standard_name)}<small>${esc(row.version||'版本未录入')} · ${esc(row.clause||'章节级片段')} · P${row.page}${row.page_end>row.page?'–'+row.page_end:''}</small><small>${esc(row.page_kind)} · ${esc(types[row.source_type])}</small>${row.is_demo?'<small class="demo-tag">DEMO / 非真实规范</small>':''}</button>`;}
function renderAnswer(a){return `<article class="answer"><h3>结论</h3><p>${esc(a.conclusion)}</p><h3>规范依据</h3>${a.citations.length?a.citations.map((r,i)=>`${citation(r,i)}<blockquote>${esc(r.text)}</blockquote>`).join(''):'<p>没有可展示的规范条文。</p>'}<h3>分析</h3><p>${esc(a.analysis)}</p><h3>注意事项</h3>${a.notes.map(n=>`<p>• ${esc(n)}</p>`).join('')}<h3>可信度：${esc(a.confidence)}</h3><p>${esc(a.confidence_reason)}</p>${a.references.length?'<h3>参考资料（不是规范依据）</h3>'+a.references.map((r,i)=>citation(r,i)).join(''):''}<details><summary>查看 Agent 检索过程</summary>${a.trace.map(t=>`<p>${esc(t.tool)}：${esc(t.detail)} ${t.count!==undefined?' · '+t.count+' 条':''}</p>`).join('')}</details></article>`;}
function evidence(a){lastAnswer=a;$('#evidence-list').innerHTML=a.citations.map(citation).join('')||'<div class="empty">未检索到明确规范依据</div>';}
$('#chat-form').onsubmit=async e=>{e.preventDefault();const q=$('#question').value.trim();if(q.length<2)return;$('#send').disabled=true;$('#send').textContent='正在检索…';await safe(async()=>{const a=await api('/chat',json({question:q,conversation_id:conversationId}));conversationId=a.conversation_id;if($('#messages .welcome'))$('#messages').innerHTML='';$('#messages').insertAdjacentHTML('beforeend',`<div class="user-message">${esc(q)}</div>${renderAnswer(a)}`);evidence(a);$('#question').value='';await loadHistory();});$('#send').disabled=false;$('#send').textContent='检索依据 →';};
async function loadHistory(){$('#history').innerHTML=(await api('/conversations')).map(r=>`<button data-history="${r.id}">${esc(r.title)}</button>`).join('');}
async function loadDocs(){docs=await api('/documents');renderDocs();}
function renderDocs(){const term=$('#document-filter').value.toLowerCase();const list=docs.filter(r=>JSON.stringify(r).toLowerCase().includes(term));$('#documents').innerHTML=list.map(r=>`<tr><td><strong>${esc(r.standard_name)}</strong><small>${esc(r.standard_code||'编号未录入')}</small>${r.is_demo?'<span class="warning">DEMO / 非真实规范</span>':''}</td><td>${esc(r.version||'未录入')}<small>${esc(r.lifecycle)}</small></td><td>${esc(types[r.source_type])}<small>${esc(r.standard_type)} / ${esc(r.category)}</small></td><td>${r.chunk_count}</td><td>${esc(r.status)}<small>${new Date(r.created_at).toLocaleDateString('zh-CN')}</small><small class="warning">${esc(r.warning)}</small></td><td><button data-doc-clauses="${r.document_id}">条文</button><button data-doc-edit="${r.document_id}">版本/分类</button><button data-doc-reparse="${r.document_id}">重新解析</button><button data-doc-delete="${r.document_id}">删除</button></td></tr>`).join('')||'<tr><td colspan="6">暂无资料，请上传 PDF、DOCX 或 TXT。</td></tr>';}
$('#document-filter').oninput=renderDocs;$('#refresh-docs').onclick=()=>safe(loadDocs);$('#upload-toggle').onclick=()=>$('#upload-form').hidden=!$('#upload-form').hidden;
$('#upload-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='解析中…';await safe(async()=>{const fd=new FormData(e.target),meta={};for(const[k,v]of fd)if(k!=='file')meta[k]=v;const payload=new FormData();payload.append('file',fd.get('file'));payload.append('metadata',JSON.stringify(meta));await api('/documents',{method:'POST',body:payload});e.target.reset();e.target.hidden=true;await loadDocs();});button.disabled=false;button.textContent='上传并解析';await loadDocs().catch(e=>notice(e.message));};
$('#search-form').onsubmit=e=>{e.preventDefault();safe(async()=>{const rows=await api('/search',json({question:$('#search-input').value}));$('#search-results').innerHTML=rows.map((r,i)=>citation(r,i)+`<small>BM25 ${r.bm25_score} · 向量 ${r.vector_score} · 融合 ${r.score}</small>`).join('')||'<p>未检索到相关资料。</p>';});};
async function loadRules(){allRules=await api('/rules');$('#rule-list').innerHTML=allRules.map(r=>`<article class="panel"><span class="badge">设计判据 · 不是规范</span><h3>${esc(r.title)}</h3><p>适用条件：${esc(r.condition)}</p><blockquote>${esc(r.rule)}</blockquote><p>例外：${esc(r.exceptions)}<br>来源：${esc(r.source)}</p><button data-rule-edit="${r.id}">编辑</button> <button data-rule-delete="${r.id}">删除</button></article>`).join('')||'<p class="muted">尚未录入设计判据。</p>';}
$('#rule-form').onsubmit=e=>{e.preventDefault();safe(async()=>{await api(editingRule?'/rules/'+editingRule:'/rules',json(Object.fromEntries(new FormData(e.target)),editingRule?'PUT':'POST'));resetRule();await loadRules();});};
function resetRule(){editingRule=null;$('#rule-form').reset();$('#rule-form-title').textContent='新增设计判据';$('#rule-cancel').hidden=true;}$('#rule-cancel').onclick=resetRule;
async function loadSettings(){const s=await api('/settings');$('#settings-data').innerHTML=`<p>检索条数：${s.top_k}<br>外部 API：${s.allow_external_api?'已显式开启':'关闭（默认）'}<br>向量模型：${esc(s.embedding)}<br>可选模型：${s.llm_configured?'已配置':'未配置，使用本地证据模式'}</p>`;}
function openDetail(title,html){$('#detail-title').textContent=title;$('#detail-body').innerHTML=html;$('#detail').showModal();}$('#close-detail').onclick=()=>$('#detail').close();
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.dataset.clause)safe(async()=>{const c=await api('/clauses/'+b.dataset.clause),d=c.document,r=c.clause;const file='/api/documents/'+d.document_id+'/file';openDetail('来源核对',`<h3>${esc(d.standard_name)}</h3><p>${esc(d.standard_code)} · ${esc(d.version)} · ${esc(types[d.source_type])}${d.is_demo?' · DEMO / 非真实规范':''}<br>章节：${esc(r.chapter)} / ${esc(r.section)}<br>条号：${esc(r.clause||'未可靠识别')} · P${r.page}–${r.page_end} · ${esc(r.page_kind)}<br>原始文件：${esc(d.filename)}</p><a href="${file}${d.filename.toLowerCase().endsWith('.pdf')?'#page='+r.page:''}" target="_blank" rel="noopener">打开原始文件${d.filename.toLowerCase().endsWith('.pdf')?'并定位到页码':''}</a><h3>条文与相邻上下文</h3>${c.context.map(x=>`<blockquote>${esc(x.text)}</blockquote>`).join('')}${d.filename.toLowerCase().endsWith('.pdf')?`<iframe title="原始 PDF" src="${file}#page=${r.page}"></iframe>`:''}`);});
if(b.dataset.history)safe(async()=>{conversationId=b.dataset.history;const messages=await api('/conversations/'+conversationId);$('#messages').innerHTML=messages.map(r=>`<div class="user-message">${esc(r.question)}</div>${renderAnswer(r.answer)}`).join('');if(messages.length)evidence(messages.at(-1).answer);view('chat');});
if(b.dataset.docClauses)safe(async()=>{const rows=await api('/documents/'+b.dataset.docClauses+'/clauses');openDetail('解析结果 / Chunk',rows.map(r=>`<h3>${esc(r.clause||r.title||'章节片段')} · P${r.page}–${r.page_end} · ${esc(r.parse_quality)}</h3><blockquote>${esc(r.text)}</blockquote>`).join('')||'<p>没有解析条文，请检查状态。</p>');});
if(b.dataset.docReparse)safe(async()=>{b.disabled=true;try{await api('/documents/'+b.dataset.docReparse+'/reparse',{method:'POST'});}finally{b.disabled=false;await loadDocs();}});
if(b.dataset.docDelete&&confirm('删除这份资料、原始文件及其索引？'))safe(async()=>{await api('/documents/'+b.dataset.docDelete,{method:'DELETE'});await loadDocs();});
if(b.dataset.docEdit){const r=docs.find(d=>d.document_id===b.dataset.docEdit);openDetail('版本与分类管理',`<form id="edit-meta" data-id="${r.document_id}"><div class="form-grid">${['standard_name','standard_code','version','publication_date','effective_date','category','supersedes'].map((k,i)=>`<label>${['名称','编号','版本','发布日期','实施日期','专业分类','替代版本'][i]}<input name="${k}" value="${esc(r[k])}" ${k==='standard_name'?'required':''}></label>`).join('')}<label>资料类型<select name="source_type">${Object.entries(types).map(([k,v])=>`<option value="${k}" ${k===r.source_type?'selected':''}>${v}</option>`).join('')}</select></label><label>标准分类<select name="standard_type">${['国家标准','行业标准','能源行业标准','国网企业标准','南网企业标准','设计院内部规定','其他'].map(v=>`<option ${v===r.standard_type?'selected':''}>${v}</option>`).join('')}</select></label><label>版本状态<select name="lifecycle">${['现行','废止','被替代','待核验'].map(v=>`<option ${v===r.lifecycle?'selected':''}>${v}</option>`).join('')}</select></label></div><button class="primary">保存修改</button></form>`);$('#edit-meta').onsubmit=e=>{e.preventDefault();safe(async()=>{await api('/documents/'+r.document_id,json(Object.fromEntries(new FormData(e.target)),'PATCH'));$('#detail').close();await loadDocs();});};}
if(b.dataset.ruleDelete&&confirm('删除这个设计判据？'))safe(async()=>{await api('/rules/'+b.dataset.ruleDelete,{method:'DELETE'});await loadRules();});
if(b.dataset.ruleEdit){editingRule=b.dataset.ruleEdit;const r=allRules.find(x=>x.id===editingRule);for(const key of ['title','category','condition','rule','exceptions','source'])$('#rule-form').elements[key].value=r[key];$('#rule-form-title').textContent='修改设计判据';$('#rule-cancel').hidden=false;}
});
safe(async()=>{const s=await api('/settings');for(const name of ['source_type','standard_type'])$(`#upload-form select[name="${name}"]`).innerHTML=(name==='source_type'?s.source_types:s.standard_types).map(v=>`<option value="${esc(v)}">${esc(types[v]||v)}</option>`).join('');await loadHistory();});
